# Last update: 21/11/2024
name: eda-env
channels:
  - conda-forge
dependencies:
  - jupyterlab=3.6.6
  - python=3.11.7
  - pandas=2.2
  - seaborn=0.13.2
  - matplotlib=3.8.2
  - numpy=1.26.3
  - wordcloud=1.9.2